CREATE DATABASE `lexerapp` /*!40100 DEFAULT CHARACTER SET latin1 */;

CREATE TABLE `LEX_FORM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS` varchar(45) DEFAULT NULL,
  `CONTENT` longtext,
  `OPDATE` date NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
